# Generated by Django 4.2.2 on 2023-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_writetous'),
    ]

    operations = [
        migrations.AddField(
            model_name='writetous',
            name='author',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
