# Generated by Django 4.2.2 on 2023-06-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_writetous_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writetous',
            name='author',
            field=models.CharField(default='Aliyar', max_length=100),
        ),
    ]
